/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chompgame;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author jan
 */
public class ClientChompGame extends javax.swing.JFrame {

    ClientPrev client;
    private ObjectInputStream sInput;
    
    /**
     * Creates new form ChompGame
     */
    public ClientChompGame() {
        initComponents();
        setButtonsIcon();
        giveAInformation();
        setDefaultFrame();
    }
    
    public void setDefaultFrame() {
        jPanel1.setVisible(false);
        this.setSize(540, 230);
        jLabel1.setVisible(false);
    }
    
    public void giveAInformation() {
        JOptionPane.showMessageDialog(this, "Chomp Chomp Game'e hoşgeldiniz. Ekranda gördüğünüz bir\n"
                + "çikolatadır. Ekranın sol alt köşesinde gördüğünüz çikolata\nparçası zehirli parçadır. "
                + "Amacınız bu parçayı rakibinize yedirmektir.\nEkranda gördüğünüz herhangi bir çikolata "
                + "parçasına dokunmanız halinde\ndokunduğunuz parçanın sağ ve üst tarafındaki parçaları da "
                + "yemiş\nolacaksınız. İyi eğlenceler!!", "Nasıl Oynanır?", JOptionPane.INFORMATION_MESSAGE);        
    }
    
    public void setButtonsIcon() {
        JButton[] buttons = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButton10, jButton18, jButton12, jButton13, jButton14, jButton15, jButton16, jButton17, jButton19};
        for (int i = 0; i < buttons.length; i++) {
            buttons[i].setIcon(new ImageIcon(System.getProperty("user.dir") + "/ci.png"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chomp Chomp Game");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 71, 72, 65));

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 142, 72, 65));

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 142, 72, 65));

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 142, 72, 65));

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 142, 72, 65));

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 72, 65));

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 71, 72, 65));

        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 142, 72, 65));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 72, 65));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 0, 72, 65));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 0, 72, 65));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 0, 72, 65));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 0, 72, 65));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 72, 65));

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 71, 72, 65));

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 71, 72, 65));

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 71, 72, 65));

        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonAction(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 72, 65));

        jLabel3.setText("Sıra Onda");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 57, -1, -1));

        jLabel2.setText("Oyuna hoşgeldiniz, oyuncu aramak için tıklayınız.");

        jButton11.setText("Oyuncu Ara");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setText("Aranıyor...");

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void commonButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonButtonAction
        // TODO add your handling code here:
        JButton bt = (JButton) evt.getSource();
        JButton[][] buttons = {{jButton1, jButton2, jButton3, jButton4, jButton5, jButton16}, {jButton6, jButton7, jButton8, jButton9, jButton10, jButton17}, {jButton18, jButton12, jButton13, jButton14, jButton15, jButton19}};

        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                if(buttons[i][j] == bt) {  
                    client.sendMessage(i + " " + j);
                    System.out.println(i + " " + j);
                    for (int k = 0; k < i + 1; k++) {
                        for (int l = j; l < buttons[k].length; l++) {
                            buttons[k][l].setVisible(false);
                        }
                    }
                    if(bt == jButton18) {
                        JOptionPane.showMessageDialog(this, "Kaybettiniz!!", "Oyun Bitti", JOptionPane.ERROR_MESSAGE);
                        jLabel3.setVisible(false);
                    }
                    break;
                }
            }
        }
        
        jLabel3.setText("Sıra Onda");
        
    }//GEN-LAST:event_commonButtonAction

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        client = new ClientPrev("127.0.0.1", 1500, "omerkocbil", null);
        client.start(); 
        jLabel1.setVisible(true);
        client.sendMessage("Tamam");
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(ClientChompGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText("Bulundu!!");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ClientChompGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLayeredPane1.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    public void display(String msg) {
        System.out.println(msg);
    }
    
    public static void doOperations(int first, int second) {
        JButton[][] buttons = {{jButton1, jButton2, jButton3, jButton4, jButton5, jButton16}, {jButton6, jButton7, jButton8, jButton9, jButton10, jButton17}, {jButton18, jButton12, jButton13, jButton14, jButton15, jButton19}};

        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                if(i == first && j == second) {
                    for (int k = 0; k < i + 1; k++) {
                        for (int l = j; l < buttons[k].length; l++) {
                            buttons[k][l].setVisible(false);
                        }
                    }
                    if(first == 2 && second == 0) {
                        JOptionPane pane = new JOptionPane("Kazandınız!!!", JOptionPane.WARNING_MESSAGE,
                                JOptionPane.DEFAULT_OPTION);
                        JDialog dialog = pane.createDialog("Oyun Bitti");
                        dialog.setLocation(230, 110);
                        dialog.setVisible(true);
                        jLabel3.setVisible(false);
                    }
                    break;
                }
            }
        }
        
        jLabel3.setText("Sıra Sizde");
        
    }
    
    public class ServerListenThread extends Thread {

        public void run() {
            while (true) {
                try {
                    Object msg = sInput.readObject();
                    if (msg instanceof String) {
                        String message = msg.toString();
                        
                        System.out.println(message);
                    }
                } catch (Exception e) {
                    display("Server Kapatıldı " + e);
                    break;
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientChompGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientChompGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientChompGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientChompGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientChompGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JButton jButton1 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton10 = new javax.swing.JButton();
    private javax.swing.JButton jButton11;
    public static final javax.swing.JButton jButton12 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton13 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton14 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton15 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton16 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton17 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton18 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton19 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton2 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton3 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton4 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton5 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton6 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton7 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton8 = new javax.swing.JButton();
    public static final javax.swing.JButton jButton9 = new javax.swing.JButton();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static final javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    private javax.swing.JLayeredPane jLayeredPane1;
    public static final javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables
}
